# Remote Servers, Regular Linux and KVM
# If you are running on Linux, you can set
# both to localhost, setup your ssh keys to
# connect via localhost and voila!
LNX_SRV="localhost"
KVM_SRV="localhost"

# Default Values
OCP_VERSION="latest-4.21"
DOMAIN="king.lab"
CLUSTER_NAME="cluster01"
NET_CIDR="192.168.86.0/24"
ARCH="x86_64"

# DNS Key to Auto Update via nsupdate
DNS_KEY_FILE="./update_local_dns.key"
DNS_SERVER="storage.king.lab"
DNS_REVERSE_ZONE="86.168.192.in-addr.arpa"

# VM Sizing
MEMORY="15258"
VCPU="12"
DISK="40"

# New User Credential
USER_ID="admin"
PASSWORD="Secret123"

# Pull Secret and SSH Public Key
PULL_SECRET=$(cat .pull_secret)
SSH_KEY=$(cat .ssh_key)

# API entry to double-check DNS entries
API_ADDR="api.${CLUSTER_NAME}.${DOMAIN}"
API_STATUS=""
